import { IncidentPlaybookItem, UserInteractionChoice } from '../types/index.ts';

export const INCIDENT_PLAYBOOK: Record<UserInteractionChoice, IncidentPlaybookItem> = {
  viewed_only: {
    key: 'viewed_only',
    title: 'I only viewed it',
    severity: 'MILD',
    headline: 'Low Exposure — Containment & Safe Disposal',
    summary: 'Viewing alone rarely results in compromise provided you did not click links, download files, or respond to the sender.',
    immediateSteps: [
      'Do not interact with any links, buttons, or phone numbers in the message.',
      'Mark the message or email as Spam / Phishing in your email or messaging client.',
      'Block the sender’s address, phone number, or handle.',
      'Delete the message once documented for records.',
    ],
    followUpSteps: [
      'Educate household or team members if this targeted a shared service (e.g., postal delivery, bank).',
      'Verify that your device operating system and browser remain updated with the latest security patches.',
    ],
    reportingChannels: [
      'Report directly via your platform (e.g. Forward SMS to 7726 / SPAM).',
      'Forward phishing emails to reportphishing@apwg.org and the FTC at reportfraud.ftc.gov.',
    ],
    warningNotice: 'If the email or message contained external images or tracking pixels, the sender may know your address is active. Be cautious of follow-up messages.',
  },
  clicked_link: {
    key: 'clicked_link',
    title: 'I clicked the link',
    severity: 'ELEVATED',
    headline: 'Moderate Exposure — Browser Session Sanitization',
    summary: 'Clicking untrusted links can expose IP address, browser fingerprint, and potentially download background drive-by payloads.',
    immediateSteps: [
      'Close the browser tab immediately. Do not interact with any prompts on the page.',
      'Do not enter credentials, phone numbers, or two-factor codes if prompted.',
      'Clear your browser cache, cookies, and active session tokens for the past 24 hours.',
      'Disconnect from public or untrusted Wi-Fi if currently active.',
    ],
    followUpSteps: [
      'Run a full system antimalware/antivirus scan using your OS built-in security tool (e.g., Windows Defender, macOS XProtect).',
      'Check browser downloads folder to ensure no stealth file (.iso, .exe, .zip, .apk) was secretly dropped.',
      'Monitor accounts for unexpected login alerts over the next 48 hours.',
    ],
    reportingChannels: [
      'Report the destination URL to Google Safe Browsing (safebrowsing.google.com/safebrowsing/report_phish/).',
      'Report to national cybersecurity authorities (e.g., CISA or FTC).',
    ],
    warningNotice: 'Never attempt to re-open the link to "test" or "verify" what it was.',
  },
  entered_password: {
    key: 'entered_password',
    title: 'I entered my password',
    severity: 'URGENT',
    headline: 'High Exposure — Immediate Credential Remediation',
    summary: 'The attacker likely captured your credentials in plaintext via a deceptive harvesting portal.',
    immediateSteps: [
      'Change the compromised password IMMEDIATELY by going directly to the official website (type the real domain or use your official mobile app).',
      'If you reused this password across other accounts (email, banking, shopping), change it on EVERY other service immediately.',
      'Terminate all active sessions: In account security settings, select "Sign out of all devices / Revoke all sessions".',
      'Enable Multi-Factor Authentication (MFA/2FA) using an Authenticator app (e.g., Google Authenticator) or Hardware Key. Avoid SMS MFA if possible.',
    ],
    followUpSteps: [
      'Inspect account recovery options: verify that the recovery email, phone number, and backup codes have not been altered.',
      'Check message forwarding rules or filter settings in your email client to ensure attackers did not set up silent forwarding.',
      'Use a reputable password manager to generate unique, high-entropy passwords for all services.',
    ],
    reportingChannels: [
      'Notify the legitimate company or service provider’s fraud department.',
      'File an incident report at IdentityTheft.gov if primary email or government credentials were exposed.',
    ],
    warningNotice: 'ScamGuard AI cannot guarantee account safety. You must act directly through official service portals immediately.',
  },
  shared_otp: {
    key: 'shared_otp',
    title: 'I shared an OTP',
    severity: 'CRITICAL',
    headline: 'Critical Danger — Immediate Session Hijack Alert',
    summary: 'One-Time Passcodes (OTPs) provide direct authorization for logins, money transfers, password resets, or SIM swaps. The attacker may currently have active access.',
    immediateSteps: [
      'Contact the affected bank or service immediately via their official customer helpline (use the number on the back of your card or official app).',
      'Inform the representative: "I accidentally shared an OTP with an unauthorized party. Please freeze online access and revoke all active sessions immediately."',
      'Review pending or recent transactions with the fraud prevention team.',
      'Reset your account password immediately from an uncompromised device.',
    ],
    followUpSteps: [
      'Never share another OTP. Legitimate banks and support teams NEVER ask for your OTP over phone, SMS, or chat.',
      'Switch from SMS-based 2FA to hardware security keys or authenticator apps (TOTP) where supported.',
      'Check carrier account settings to ensure no unauthorized SIM transfer or call forwarding was enabled.',
    ],
    reportingChannels: [
      'Official bank / financial institution fraud hotline.',
      'FTC Report Fraud (reportfraud.ftc.gov) or FBI Internet Crime Complaint Center (ic3.gov).',
    ],
    warningNotice: 'Time is critical. Financial institutions often have a narrow recovery window for intercepted electronic fund transfers.',
  },
  bank_details: {
    key: 'bank_details',
    title: 'I entered card/bank information',
    severity: 'CRITICAL',
    headline: 'Critical Danger — Financial Account Freeze Required',
    summary: 'Your debit/credit card number, CVV, expiration date, or bank account routing numbers are in possession of adversaries.',
    immediateSteps: [
      'Open your bank mobile app and instantly FREEZE or LOCK the affected debit or credit card.',
      'Call the bank fraud line immediately using the emergency phone number printed on the back of your physical card.',
      'Request card cancellation and issue of a replacement card with a new card number and CVV.',
      'Dispute any unauthorized or pending charges immediately with the representative.',
    ],
    followUpSteps: [
      'Request temporary restriction on electronic wire transfers or ACH debits if account numbers were compromised.',
      'Set up instant real-time SMS/push transaction alerts for all amounts greater than $0.01.',
      'Monitor your credit reports across major bureaus (Equifax, Experian, TransUnion) and consider a credit freeze.',
    ],
    reportingChannels: [
      'Your financial institution’s dedicated 24/7 fraud department.',
      'Consumer Financial Protection Bureau (cfpb.gov) and FTC (reportfraud.ftc.gov).',
    ],
    warningNotice: 'Do not use contact numbers provided in the suspicious message. Only use numbers on physical cards or verified official websites.',
  },
  transferred_money: {
    key: 'transferred_money',
    title: 'I transferred money',
    severity: 'CRITICAL',
    headline: 'Emergency Action — Fund Recall & Cybercrime Reporting',
    summary: 'Wire transfers, peer-to-peer transfers (Zelle, Venmo, CashApp), crypto transactions, or gift cards require rapid intervention.',
    immediateSteps: [
      'Contact your bank or payment platform immediately to request a WIRE RECALL or fraudulent transaction reversal.',
      'If sent via a P2P app (Zelle/Venmo/CashApp), report the transaction in-app as "Fraud / Unauthorized" and call customer support immediately.',
      'If you purchased gift cards: Contact the card issuer (Apple, Google, Amazon, Steam) immediately. If the funds have not been redeemed, they may be able to freeze the balance.',
      'Preserve all transaction receipts, reference numbers, timestamps, chat logs, and wallet addresses.',
    ],
    followUpSteps: [
      'File an official police report with your local law enforcement agency. Request an incident/case number.',
      'File a complaint with the FBI Internet Crime Complaint Center (IC3) at ic3.gov (essential for international wire recall protocols).',
      'Beware of "Recovery Scammers" who contact you claiming they can hack or recover your lost funds for an upfront fee. These are secondary scams.',
    ],
    reportingChannels: [
      'FBI Internet Crime Complaint Center (ic3.gov).',
      'Federal Trade Commission (reportfraud.ftc.gov).',
      'Local law enforcement cybercrime unit.',
    ],
    warningNotice: 'Beware of recovery scams. No legitimate agency or hacker will ask you to pay fees to recover stolen funds.',
  },
  downloaded_file: {
    key: 'downloaded_file',
    title: 'I downloaded a file',
    severity: 'URGENT',
    headline: 'High Threat — Device Isolation & Malware Remediation',
    summary: 'Downloaded attachments (.exe, .scr, .zip, .iso, .vbs, .apk, .dmg) frequently deploy trojans, infostealers, keyloggers, or ransomware.',
    immediateSteps: [
      'DO NOT open or run the downloaded file! If it is currently running, terminate the process via Task Manager / Activity Monitor.',
      'Disconnect your device from the Internet immediately (turn off Wi-Fi, unplug Ethernet cable) to prevent remote command & control or data exfiltration.',
      'Delete the downloaded file from your Downloads folder and empty your Recycle Bin / Trash.',
      'Perform an offline deep antivirus/antimalware scan using a trusted tool.',
    ],
    followUpSteps: [
      'If the file was executed: Assume credentials stored in your browser or session cookies may be compromised. Reset passwords from a DIFFERENT, clean device.',
      'Check startup items and task scheduler for suspicious scheduled tasks or unknown background processes.',
      'Backup important offline files to an external drive (after scanning) in case ransomware triggers.',
    ],
    reportingChannels: [
      'Submit the file hash or sample to VirusTotal (virustotal.com) for telemetry analysis (do not submit if it contains private personal data).',
      'Report malware distribution sites to CISA (cisa.gov/report).',
    ],
    warningNotice: 'If an infostealer ran on your system, browser-saved passwords and active cookies must be treated as compromised. Change credentials from an independent device.',
  },
  personal_info: {
    key: 'personal_info',
    title: 'I shared personal information',
    severity: 'ELEVATED',
    headline: 'Identity Risk — Credit Monitoring & Identity Theft Shield',
    summary: 'Sharing full name, address, Social Security Number, date of birth, or ID pictures enables synthetic identity fraud and targeted social engineering.',
    immediateSteps: [
      'Place a FREE Credit Freeze and Fraud Alert with the three major credit bureaus (Equifax, Experian, TransUnion).',
      'Create an account at IdentityTheft.gov to get a personalized recovery plan from the Federal Trade Commission.',
      'Alert your mobile phone carrier and request a "SIM Transfer PIN / Port Freeze" on your account to prevent SIM swapping.',
    ],
    followUpSteps: [
      'Set up credit and dark web monitoring notifications.',
      'File an IRS Identity Protection PIN (IP PIN) request to protect your tax filings from fraudulent returns.',
      'Be on high alert for hyper-personalized spear-phishing calls pretending to be law enforcement or bank representatives citing your personal details.',
    ],
    reportingChannels: [
      'Federal Trade Commission Identity Theft portal (identitytheft.gov).',
      'Social Security Administration fraud reporting if SSN was compromised (oig.ssa.gov).',
    ],
    warningNotice: 'Fraud alerts require potential creditors to verify your identity before opening new credit accounts in your name.',
  },
  unsure: {
    key: 'unsure',
    title: "I'm not sure",
    severity: 'ELEVATED',
    headline: 'Precautionary Protocol — Comprehensive Safety Check',
    summary: 'When in doubt, applying conservative defense-in-depth measures prevents silent lateral account or credential exploitation.',
    immediateSteps: [
      'Check your browser history to see if you were redirected to any unfamiliar websites.',
      'Check your downloads folder for any recently acquired files you did not intentionally download.',
      'Review your primary email account for recent login activity and foreign IP sessions.',
      'Do not respond or engage further with the suspicious message.',
    ],
    followUpSteps: [
      'Run a full system security scan with up-to-date definitions.',
      'Enable Multi-Factor Authentication on your email, financial, and social accounts.',
      'Consult the ScamGuard Security Copilot with details of what you observed.',
    ],
    reportingChannels: [
      'Report the message to your provider or forward SMS to 7726.',
    ],
    warningNotice: 'Erring on the side of caution protects your digital identity. Reset critical passwords if any doubt exists.',
  },
};
